server:
  port: 8765

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: registration
          uri: lb://worker
          predicates:
            - Path=/api/v1/registration
            - Method=POST

        - id: confirm
          uri: lb://worker
          predicates:
            - Path=/api/v1/registration/confirm
            - Method=GET

        - id: authenticate
          uri: lb://worker
          predicates:
            - Path=/api/v1/registration/authenticate
            - Method=POST


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
